### ISSUE TITLE
Google Drive Link Request

### ISSUE THREAD

**Issue by MMarvasti** [Linfeng-Tang/SeAFusion#18]
Hello,

Thanks for your excellent work. Could you provide a google drive link to your training dataset?

Thanks in advance,
Mojtaba

**Comment by Linfeng-Tang** [comment]
You can download the training dataset from: https://drive.google.com/file/d/1musDMaQxZj6kRYb8cO4ewF6FNE9G9DvV/view?usp=sharing.

**Comment by MMarvasti** [comment]
Thank you so much.
