### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by liushh39** [Linfeng-Tang/SeAFusion#38]
你好，训练一次分割器要80000次迭代，1个epoch得训练10个小时，我用的3070，是我的问题吗

**Comment by Linfeng-Tang** [comment]
是不是没有加载到GPU上面去呀。

**Comment by liushh39** [comment]
哦哦，是4个epoch10小时









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 Linfeng ***@***.***&gt; 于2024年1月14日(周日) 中午11:52写道:

  

 
是不是没有加载到GPU上面去呀。
