### ISSUE TITLE
Segmentation Net

### ISSUE THREAD

**Issue by xiyunqiao** [Linfeng-Tang/SeAFusion#4]
您好，请问论文里的语义分割网络是引用的哪篇文章？能否给个分割部分文章链接？

**Comment by xiyunqiao** [comment]
分割部分有个“auxiliary segmentation”，希望能看看这个分割的原文，没太理解这块。谢谢！

**Comment by Linfeng-Tang** [comment]
不好意思 一直没看到这个issus，论文中应该给出了分割论文的参考文献吧
