### ISSUE TITLE
请问能否只训练融合部分的模型？

### ISSUE THREAD

**Issue by amiaodemiao** [Linfeng-Tang/SeAFusion#41]
您好，请问如果只想要进行可见光和红外的融合，不需要进行分割，是否可以只训练融合部分模型？是否会对融合模型的性能产生较大的影响？

**Comment by Zshuting** [comment]
请问你试过吗？可以吗？

**Comment by amiaodemiao** [comment]
> 请问你试过吗？可以吗？

可以，是两个部分分开训练的。
